// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:826ba5bf-ed46-4537-993f-80e0339fbc7a",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_03LU9EvRK",
    "aws_user_pools_web_client_id": "2lrq7d58t7dh5rj7kdp127r1sj",
    "oauth": {
        "domain": "covid19sdbcc9ff73-bcc9ff73-dev.auth.eu-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_dynamodb_all_tables_region": "eu-west-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "dynamo9f597ff1-dev",
            "region": "eu-west-2"
        },
        {
            "tableName": "demand-dev",
            "region": "eu-west-2"
        }
    ],
    "aws_user_files_s3_bucket": "covid19sd35467e3530b849caa746ddae0ca31395191840-dev",
    "aws_user_files_s3_bucket_region": "eu-west-2",
    "aws_cloud_logic_custom": [
        {
            "name": "demandAPI",
            "endpoint": "https://2yqw9bjer6.execute-api.eu-west-2.amazonaws.com/dev",
            "region": "eu-west-2"
        }
    ]
};


export default awsmobile;
